### ISSUE TITLE
Download update file

### ISSUE THREAD

**Issue by codders** [advancedtelematic/sota_client_cpp#32]
For initial implementation, client should download the update as soon as it receives data that an update is available.

In the final client, the download will be triggered after interaction with the Software Installer

**Comment by embmk** [comment]
I uploaded a binary file to my garage account and marked it an available update. Using the branch for api request (as it is not pulled yet) I get a valid response from the server showing me the available update.

**Comment by embmk** [comment]
I am now detecting a redirect to the amazon cloud and can use it to download the file.
But the build in Docker fails for some reason. I cannot comprehend the problem as both targets test and coverage work fine when I execute them here... I already checked if the config folder gets copied into docker, as it is now used in almost all testcases.

**Comment by embmk** [comment]
I'm not shure if I should create new issues now, but when it comes to downloading files there are something that can be done different. For the start I implemented a write-callback that writes curl responses to a string. When it comes to downloading it could be reasonable to provide a callback that writes directly into a file. This requires detecting HTTP 30X redirects or getting curl configured to automatically follow redirects (which I tried, but it didn't from the scratch and I thought it might be useful to manually detect redirects). I would normally write a TODO into the code but due to current circumstances I hesitate.

**Comment by codders** [comment]
I'll have a look at the docker build. For sure we need to be using the curl file writing callback, and following HTTP30x redirects, but these are fairly minor changes.

Please file issues for these changes and note the TODOs in the code. Please also create a pull request for the code that you've built to date and clean up the history (rebase, squash).

**Comment by embmk** [comment]
As I created the branch after I quit using the git GUI that caused so much problems for me, I hope that there will be no need for intensive squashing...
